site_name: CaribData Stories
site_description: A data storytelling site for CaribData
site_url: https://caribdata.github.io/caribdata-stories
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - blog
  language: en
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep orange
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: green
      accent: deep orange

plugins:
  - search
  - blog:
      blog_dir: blog
      draft_if_future_date: true
      categories_allowed:
       - data
       - climate
       - health
       - sids
       - caribbean
      post_url_format: "{slug}/"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.superfences
#  - pymdownx.tabbed:
#      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: /fontawesome/brands/youtube
      link: https://www.youtube.com/@CaribData
    - icon: /fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/caribdata
nav:
  - Home: index.md
  - Blog:
      - blog/index.md

hooks:
  - hooks/socialmedia.py 
  